# -*- coding: utf-8 -*-
"""Random_Forest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14QP2dHhgi2GFlF3wChaDfudcsH8zlN3Y

#Cover Page

**Developed by:**

**Mohamed Waled - 41810162**

#Import the dataset from drive
"""

!gdown --id 1eBuFpD7VAbUCGwxfG5J70G3r2_Bkhqu8

"""#Importing libraries"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, classification_report, mean_absolute_error, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler,LabelEncoder

"""# show how the data looks like"""

data = pd.read_csv('winequality-white.csv',sep=';')
data.head(5)

data['quality label'] = data['quality'].apply(lambda x: 1 if x<=5 else 2 if x<=7 else 3)
print(data[['quality','quality label']].value_counts().sort_index())
data.head()

"""#Normalization"""

# df = data.drop('Type', axis=1)
# df_norm = (df-df.min())/(df.max()-df.min())
# df_norm = pd.concat((df_norm, data.Type), 1)
# df_norm.head()

"""#Start Split the data and train"""

X = data.drop('quality',axis=1)
y = data['quality']

scaler = StandardScaler()
X = pd.DataFrame(scaler.fit_transform(X), columns=X.columns)
X.head()

print(X.shape)
print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state=0, stratify=data['quality label'])
print(len(X_train), "train +", len(X_test), "valid")

"""#Using Random_Forest for trainning """

model = RandomForestClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
cm

sns.heatmap(cm, annot=True)
plt.xlabel('Prediction')
plt.ylabel('Truth')

"""**Accuracy** """

var="%"
print("Accuracy: %0.1f" % (model.score(X_test,y_test)*100), var[0])

"""#find the mean square error"""

lin_mse = mean_squared_error(y_test, y_pred)
lin_rmse = np.sqrt(lin_mse)
lin_rmse

lin_mae = mean_absolute_error(y_test, y_pred)
lin_mae

"""# Classification Report"""

print(classification_report(y_test, y_pred))

